---
title: "ASSIGNMENT #2: EXPLORATORY DATA ANALYSIS WITH GGPLOT2"
author: "Group F"
date: "DEC/13/2020"
output:
  html_document:
  code_folding: show
toc: true
toc_float:
  collapsed: false
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Start

Set the folder (path) that contains this R file as the working directory

```{r}
library(tidyverse)
library(skimr)
library(ggpmisc)
library(lubridate)
library(ggridges)
library(ggalluvial)

# dir <- dirname(rstudioapi::getActiveDocumentContext()$path)
# setwd(dir)
```

## Load data

Read the raw data from the CSV file.

```{r}
df <- read_delim(file="source/madrid_transactions.csv", delim = ',', locale = locale(decimal_mark = '.'))
```

```{r}
df
```


## Quick EDA

```{r}
skim(df)
```

```{r}
table(lapply(df['tx_date_proc'], function(x) format(x, "%Y-%m-%d")))
```


```{r}

# Correlation
# http://www.sthda.com/english/wiki/correlation-matrix-a-quick-start-guide-to-analyze-format-and-visualize-a-correlation-matrix-using-r-software
library("PerformanceAnalytics")
my_data <- df %>% 
  mutate_if(is.character, function(x) as.numeric(as.factor(x))) %>% 
  select(-tx_date_proc)
chart.Correlation(my_data, histogram=TRUE, pch=19)
```

```{r}
theme_set(theme_ridges())
```


```{r}
# Data pre processing
df_top <- df %>% 
  group_by(`customer_country`) %>% 
  summarise(Total=sum(`amount`)) %>% 
  top_n(5, Total) %>%
  arrange(desc(Total))

df_grouped <- df %>% 
  mutate(top_customer_country=ifelse(`customer_country` %in% df_top[['customer_country']], `customer_country`, 'Other')) %>% 
  mutate(top_customer_country=factor(top_customer_country, levels=c(df_top[['customer_country']], 'Other')))

mu <- df_grouped %>% 
  group_by(top_customer_country) %>% 
  summarise(grp.mean=mean(amount))

# Change line colors by groups
ggplot(df_grouped, aes(x=amount, color=top_customer_country, fill=top_customer_country)) +
  # geom_histogram(aes(y=..density..), position="identity", alpha=0.5)+
  geom_density(alpha=0.1)+
  geom_vline(data=mu, aes(xintercept=grp.mean, color=top_customer_country), linetype="dashed")+
  labs(title="Amount per country",x="Amount in log scale", y = "Density")+
  theme_classic() +
  scale_x_log10()
```



```{r}
ggplot(df_grouped, aes(x=amount, y=top_customer_country, fill=top_customer_country)) +
  geom_boxplot() +
  scale_x_log10() +
  theme(legend.position = "none")
```

```{r}
# Data pre processing
df_top <- df %>% 
  group_by(`category`) %>% 
  summarise(Total=sum(`amount`)) %>% 
  top_n(5, Total) %>%
  arrange(desc(Total))

df_grouped <- df %>% 
  mutate(top_=ifelse(`category` %in% df_top[['category']], `category`, 'Other')) %>% 
  mutate(top_=factor(top_, levels=c(df_top[['category']], 'Other')))
  # filter(customer_country=='US')

mu <- df_grouped %>% 
  group_by(top_) %>% 
  summarise(grp.mean=mean(amount))

# Change line colors by groups
ggplot(df_grouped, aes(x=amount, color=top_, fill=top_)) +
  # geom_histogram(aes(y=..density..), position="identity", alpha=0.5)+
  geom_density(alpha=0.1)+
  geom_vline(data=mu, aes(xintercept=grp.mean, color=top_), linetype="dashed")+
  labs(title="Amount per category",x="Amount", y = "Density") +
  scale_x_log10()
```



```{r}
# https://rkabacoff.github.io/datavis/Other.html
library(ggplot2)
library(ggalluvial)

df_grouped <- df_grouped %>% 
  group_by(top_, daytime, weekday) %>% 
  summarise(amount=sum(amount))
            
ggplot(df_grouped, aes(axis1 = top_,
           axis2 = daytime,
           y = amount)) +
  geom_alluvium(aes(fill = weekday)) +
  geom_stratum() +
  geom_text(stat = "stratum", aes(label = after_stat(stratum))) +
  scale_x_discrete(limits = c("Category", "Daytime"), expand = c(.1, .1)) +
  labs(title = "Titanic data", subtitle = "stratified by class, sex, and survival", y = "Frequency") +
  theme_minimal()
```




```{r}
df_top_category <- df %>% 
  group_by(`category`) %>% 
  summarise(Total=sum(`amount`)) %>% 
  top_n(5, Total) %>%
  arrange(desc(Total))

df_top_country <- df %>% 
  group_by(`customer_country`) %>% 
  summarise(Total=sum(`amount`)) %>% 
  top_n(5, Total) %>%
  arrange(desc(Total))

df_grouped <- df %>% 
  mutate(top_category=ifelse(`category` %in% df_top_category[['category']], `category`, 'Other')) %>% 
  mutate(top_category=factor(top_category, levels=c(df_top_category[['category']], 'Other'))) %>% 
  mutate(top_country=ifelse(`customer_country` %in% df_top_country[['customer_country']], `customer_country`, 'Other')) %>% 
  mutate(top_country=factor(top_country, levels=c(df_top_country[['customer_country']], 'Other')))

mu <- df_grouped %>% 
  group_by(top_category) %>% 
  summarise(grp.mean=mean(amount))

ggplot(df_grouped, aes(x=amount, color=top_category, fill=top_category)) +
  facet_wrap(vars(top_country)) +
  geom_density(alpha=0.1)+
  geom_vline(data=mu, aes(xintercept=grp.mean, color=top_category), linetype="dashed")+
  labs(title="Amount per category",x="Amount", y = "Density") +
  coord_cartesian(xlim = c(0, 200), ylim = c(0, 0.02)) +
  scale_color_discrete(name = "Category") +
  scale_fill_discrete(name = "Category")
```


```{r}
# https://www.analyzemath.com/parabola/three_points_para_calc.html

f <-  function(x) −0.03667*x^2+4.833*x+500.0

df_grouped <- df %>% 
  group_by(customer_country) %>% 
  summarise(AverageAmount=mean(amount),
            TransactionsCount=n()) %>% 
  mutate(color_=TransactionsCount>=f(AverageAmount),
         label_=ifelse(color_, customer_country, ''))


ggplot(df_grouped, aes(x=AverageAmount, y=TransactionsCount)) +
  geom_rect(aes(xmin = 50, xmax = 150, ymin = 1000, ymax = 1800), alpha=0.2, fill="red") +
  geom_rect(aes(xmin = 250, xmax = 500, ymin = 0, ymax = 200), alpha=0.2, fill="green") +
  geom_point(aes(color=color_)) +
  geom_text(aes(label=label_)) +
  geom_function(fun = f, xlim=c(0, 200)) +
  theme(legend.position = "none")
```


```{r}
ggplot() +
  geom_rect(aes(xmin = 50, xmax = 150, ymin = 1000, ymax = 1800), alpha=0.2, fill="red") +
  annotate("text", x = 200, y = 1500, label = "Spend more", color = 'red') +
  geom_rect(aes(xmin = 250, xmax = 500, ymin = 0, ymax = 200), alpha=0.2, fill="green") +
  annotate("text", x = 400, y = 300, label = "More transactions", color = 'dark green') +
  geom_point(data=df_grouped, aes(x=AverageAmount, y=TransactionsCount, color=color_)) +
  geom_text(data=df_grouped, aes(x=AverageAmount, y=TransactionsCount, label=label_), nudge_y = 100) +
  geom_function(data=df_grouped, aes(x=AverageAmount), fun = f, xlim=c(0, 200)) +
  theme(legend.position = "none") +
  labs(title="Growth areas",x="Average amount", y = "Transactions count")
```


```{r}
ggplot() + 
  # geom_density(data=mtcars, aes(x=disp, group=cyl, fill=cyl), alpha=0.6, adjust=0.75) +
  geom_rect(aes(xmin=100, xmax=200, ymin=0,ymax=Inf), alpha=0.2, fill="red")
```


```{r}
set.seed(1492)
base <- ggplot(data.frame(x = rnorm(100)), aes(x)) +
  geom_density()

f <- function(x) 0.5*exp(-abs(x))
base + geom_function(fun = f)

```


```{r}
df_top_category <- df %>% 
  group_by(`category`) %>% 
  summarise(Total=sum(`amount`)) %>% 
  top_n(5, Total) %>%
  arrange(desc(Total))

df_top_country <- df %>% 
  group_by(`customer_country`) %>% 
  summarise(Total=sum(`amount`)) %>% 
  top_n(5, Total) %>%
  arrange(desc(Total))

df_grouped <- df %>% 
  mutate(top_category=ifelse(`category` %in% df_top_category[['category']], `category`, 'Other')) %>% 
  mutate(top_category=factor(top_category, levels=c(df_top_category[['category']], 'Other'))) %>% 
  mutate(top_country=ifelse(`customer_country` %in% df_top_country[['customer_country']], `customer_country`, 'Other')) %>% 
  mutate(top_country=factor(top_country, levels=c(df_top_country[['customer_country']], 'Other')))

mu <- df_grouped %>% 
  group_by(top_country) %>% 
  summarise(grp.mean=mean(amount))

ggplot(df_grouped, aes(x=amount, color=top_country, fill=top_country)) +
  facet_wrap(vars(top_category)) +
  geom_density(alpha=0.1)+
  geom_vline(data=mu, aes(xintercept=grp.mean, color=top_country), linetype="dashed")+
  labs(title="Amount per category",x="Amount", y = "Density") +
  coord_cartesian(xlim = c(0, 200), ylim = c(0, 0.02)) +
  scale_color_discrete(name = "Country") +
  scale_fill_discrete(name = "Country")
```


```{r}
df_top_category <- df %>% 
  group_by(`category`) %>% 
  summarise(Total=sum(`amount`)) %>% 
  top_n(5, Total) %>%
  arrange(desc(Total))

df_top_country <- df %>% 
  group_by(`customer_country`) %>% 
  summarise(Total=sum(`amount`)) %>% 
  top_n(5, Total) %>%
  arrange(desc(Total))

df_grouped <- df %>% 
  mutate(top_category=ifelse(`category` %in% df_top_category[['category']], `category`, 'Other')) %>% 
  mutate(top_category=factor(top_category, levels=c(df_top_category[['category']], 'Other'))) %>% 
  mutate(top_country=ifelse(`customer_country` %in% df_top_country[['customer_country']], `customer_country`, 'Other')) %>% 
  mutate(top_country=factor(top_country, levels=c(df_top_country[['customer_country']], 'Other')))


df_grouped <- df_grouped %>% 
  group_by(top_category, top_country) %>% 
  summarise(sum_=sum(amount)/1e3)

gg <- ggplot(df_grouped, aes(x = top_category, y = sum_, fill = top_country, label = paste(top_country, "\n", round(sum_, 0)))) +  # Create stacked bar chart
  geom_bar(stat = "identity") +
  geom_text(size = 3, position = position_stack(vjust = 0.5)) +
  theme(axis.text.x=element_text(angle=90, hjust=1)) +
  coord_flip()

gg     
```


```{r}
# Data pre processing
df_top <- df %>% 
  group_by(`category`) %>% 
  summarise(Total=sum(`amount`)) %>% 
  top_n(5, Total) %>%
  arrange(desc(Total))

df_grouped <- df %>% 
  mutate(top_=ifelse(`category` %in% df_top[['category']], `category`, 'Other')) %>% 
  mutate(top_=factor(top_, levels=c(df_top[['category']], 'Other'))) %>% 
  group_by(hour, top_) %>% 
  summarise(total_amount=mean(amount))

# Change line colors by groups
ggplot(df_grouped, aes(x=hour, y=total_amount, color=top_)) +
  geom_line() +
  labs(title="Amount per category",x="Hour", y = "Average amount")
```


```{r}
# Data pre processing
df_top <- df %>% 
  group_by(`category`) %>% 
  summarise(Total=sum(`amount`)) %>% 
  top_n(5, Total) %>%
  arrange(desc(Total))

df_grouped <- df %>% 
  mutate(top_=ifelse(`category` %in% df_top[['category']], `category`, 'Other')) %>%
  mutate(top_=factor(top_, levels=c(df_top[['category']], 'Other'))) %>% 
  group_by(hour, top_) %>% 
  summarise(n=n())

# Change line colors by groups
ggplot(df_grouped, aes(x=hour, y=n, color=top_)) +
  geom_line() +
  labs(title="Total number of transactions per hour",x="Hour", y = "Number of transactions") +
  scale_color_discrete(name = "Category")
```





```{r}
# Data pre processing
df_top <- df %>% 
  group_by(`category`) %>% 
  summarise(Total=sum(`amount`)) %>% 
  top_n(5, Total) %>%
  arrange(desc(Total))

daytime_sorted <- df %>% 
  group_by(`daytime`) %>% 
  summarise(hour=mean(`hour`)) %>% 
  arrange((hour)) %>% 
  .[['daytime']]

df_grouped <- df %>% 
  mutate(top_=ifelse(`category` %in% df_top[['category']], `category`, 'Other')) %>%
  mutate(top_=factor(top_, levels=c(df_top[['category']], 'Other'))) %>% 
  mutate(daytime=factor(daytime, levels=daytime_sorted)) %>% 
  group_by(`daytime`, top_) %>% 
  summarise(n=n())

# Change line colors by groups
ggplot(df_grouped, aes(x=`daytime`, y=n, color=top_, group=top_)) +
  geom_point(stat='summary') +
  stat_summary(fun.y=sum, geom="line")
  labs(title="Total number of transactions per daytime", x="Weekday", y = "Number of transactions") +
  scale_color_discrete(name = "Category")
```

## Map

```{r}
# https://rpubs.com/Lluis_Ramon/Prestantacion_ggplot2_ggmap
# https://www.datanovia.com/en/blog/how-to-create-a-map-using-ggplot2/
library(maptools)
library(maps)

data(wrld_simpl)
world_ggmap <- fortify(wrld_simpl, region = "ISO2")

df_grouped <- df %>% 
  group_by(`customer_country`, `category`) %>% 
  summarise(n_=n(),
            amount_=sum(amount)) %>% 
  mutate(row_=row_number())

df_top_country <- df %>% 
  group_by(`customer_country`) %>% 
  summarise(Total=sum(`amount`)) %>% 
  top_n(5, Total) %>%
  arrange(desc(Total)) %>% 
  .[['customer_country']]

world_ggmap_mean <- world_ggmap %>%
  group_by(id) %>%
  summarise(long = mean(long), lat = mean(lat)) %>% 
  filter(id %in% df_top_country)

gg <- ggplot(df_grouped) +
  geom_map(aes(map_id = customer_country, fill = n_), map = world_ggmap) +
  expand_limits(x = world_ggmap$long, y = world_ggmap$lat) +
  geom_text(aes(x=long, y=lat, label = id), data=world_ggmap_mean, size = 3, hjust = 0.5, color='red')+
  scale_fill_viridis_c()+
  theme_void() +
  theme(legend.position = "none")

gg
```

```{r}
gg +
  facet_wrap(vars(category))
```


```{r}

df_top <- df %>% 
  group_by(`category`) %>% 
  summarise(Total=sum(`amount`)) %>% 
  top_n(5, Total) %>%
  arrange(desc(Total))

df_grouped <- df %>% 
  mutate(top_=ifelse(`category` %in% df_top[['category']], `category`, 'Other')) %>%
  mutate(top_=factor(top_, levels=c(df_top[['category']], 'Other')))

ggplot(df_grouped, aes(x=tx_date_proc, y=amount)) +
  geom_smooth() +
  facet_wrap(vars(top_))
```

## 2D density

```{r}

df_grouped <- df %>% 
  mutate(day_hour_=floor_date(tx_date_proc, "hour"))
  # group_by(day_hour_, category) %>% 
  # summarise(mean_=log10(mean(amount))) 

ggplot(df_grouped, aes(x=log10(amount))) +
  facet_wrap(vars(category)) +
  geom_density(alpha=0.1)+
  coord_cartesian(xlim = c(-1, 4), ylim = c(0, 1)) +
  scale_color_discrete(name = "Category") +
  scale_fill_discrete(name = "Category")
  # labs(title="Amount per category",x="Amount", y = "Density") +
```


```{r}
library(scales)

df_grouped <- df %>% 
  mutate(day_hour_=floor_date(tx_date_proc, "hour"),
         hour_=make_datetime(
                hour = hour(tx_date_proc),
                min = minute(tx_date_proc),
                sec = second(tx_date_proc)))

ggplot(df_grouped, aes(x=hour_, color=weekday)) +
  facet_wrap(vars(category)) +
  geom_density(alpha=0.1) +
  theme(axis.text.x=element_text(angle=90, hjust=1)) +
  coord_cartesian(ylim = c(0, 0.00005))
```

```{r}
df_grouped <- df %>% 
  mutate(day_hour_=floor_date(tx_date_proc, "hour"),
         hour_=make_datetime(
                hour = hour(tx_date_proc),
                min = minute(tx_date_proc),
                sec = second(tx_date_proc)))

ggplot(df_grouped, aes(x=hour, color=weekday)) +
  facet_wrap(vars(category)) +
  geom_density(alpha=0.1) +
  theme(axis.text.x=element_text(angle=90, hjust=1), axis.text.y = element_blank())
```

```{r}
df_grouped <- df %>% 
  mutate(day_hour_=floor_date(tx_date_proc, "hour"),
         hour_=make_datetime(
                hour = hour(tx_date_proc),
                min = minute(tx_date_proc),
                sec = second(tx_date_proc))) %>% 
  group_by(category, hour) %>% 
  summarise(n_=n(),
            sum_=sum(amount),
            mean_=mean(amount))

ggplot(df_grouped, aes(x=hour, y=category, fill=sum_)) +
  geom_tile(alpha=0.8) +
  theme(axis.text.x=element_text(angle=90, hjust=1)) +
  scale_fill_viridis_c(name = "Spenditure") +
  labs(title = "Categories spendings",
       subtitle = "Total spenditure",
       y = "Category",
       x = "Hour of the day")
```


```{r}

df_sort <- df %>% 
  group_by(category) %>% 
  summarise(n_=n(),
            sum_=sum(amount),
            mean_=mean(amount)) %>% 
  arrange((sum_)) %>% 
  .[['category']]

df_grouped <- df %>% 
  group_by(category, hour) %>% 
  summarise(n_=n(),
            sum_=sum(amount),
            mean_=mean(amount)) %>% 
  mutate(category = factor(category, df_sort))
  # mutate(category=fct_reorder(.f=`category`, .x=sum_, .desc=F))

ggplot(df_grouped, aes(y=category, x=sum_, fill=category)) +
  geom_density_ridges(alpha=0.7) +
  labs(title = "Categories spendings",
         subtitle = "Aggregated by Hours",
         y = "Category",
         x = "Total Spending") +
  theme(legend.position = "none") +
  scale_fill_viridis_d()
```



```{r}
# https://public.tableau.com/en-us/gallery/evolution-global-temperature
df_mod <- df %>% 
  mutate(day_hour_=floor_date(tx_date_proc, "hour"),
         minute_=minute(tx_date_proc)) %>% 
  group_by(day_hour_, minute_, category) %>% 
  summarise(mean_=log10(mean(amount))) 
  
gg <- ggplot(df_mod) +
  geom_raster(aes(x=day_hour_, y=minute_, fill = mean_), hjust=0.5, vjust=0.5, interpolate=FALSE) +
  facet_wrap(vars(category)) +
  scale_fill_viridis_c() +
  theme(axis.text.x=element_text(angle=90, hjust=1))

gg
```

```{r}
# https://public.tableau.com/en-us/gallery/evolution-global-temperature
df_mod <- df %>% 
  mutate(day_hour_=floor_date(tx_date_proc, "hour"),
         minute_=minute(tx_date_proc)) %>% 
  group_by(day_hour_, minute_, category) %>% 
  summarise(n_=n()) 
  
gg <- ggplot(df_mod) +
  geom_raster(aes(x=day_hour_, y=minute_, fill = n_), hjust=0.5, vjust=0.5, interpolate=FALSE) +
  facet_wrap(vars(category)) +
  scale_fill_viridis_c() +
  theme(axis.text.x=element_text(angle=90, hjust=1))

gg
```


## 3D

```{r}
# https://www.tylermw.com/3d-ggplots-with-rayshader/
# remotes::install_github("tylermorganwall/rayshader")
library(rayshader)
# plot_gg(gg,multicore=TRUE,width=5,height=5,scale=250)
```




```{r}
# http://www.sthda.com/english/articles/32-r-graphics-essentials/133-plot-one-variable-frequency-graph-density-distribution-and-more/
df_mod <- df %>% 
  mutate(day_hour_=floor_date(tx_date_proc, "hour"),
         minute_=factor(round(minute(tx_date_proc), -1)))
  
ggplot(df_mod) +
  geom_density_ridges_gradient(aes(x=day_hour_, y=minute_, fill=..x..), scale = 3, size = 0.3) +
  theme(axis.text.x=element_text(angle=90, hjust=1)) +
  facet_wrap(vars(category)) +
  theme(legend.position = "none")
```

```{r}
# http://www.sthda.com/english/articles/32-r-graphics-essentials/133-plot-one-variable-frequency-graph-density-distribution-and-more/
# https://stackoverflow.com/questions/25985159/r-how-to-3d-density-plot-with-gplot-and-geom-density
ggplot(df) +
  geom_density_ridges_gradient(aes(x=tx_date_proc, y=category, fill=..x..), scale = 3, size = 0.3) +
  theme(axis.text.x=element_text(angle=90, hjust=1)) +
  theme(legend.position = "none")
```


```{r}
df_mod <- df %>% 
  mutate(day_hour_=floor_date(tx_date_proc, "hour"),
         minute_=minute(tx_date_proc))
  
ggplot(df_mod) +
  geom_hex(aes(x=minute_, y=log10(amount))) +
  facet_wrap(vars(factor(day_hour_))) +
  scale_fill_viridis_c() +
  theme(axis.text.x=element_text(angle=90, hjust=1))
```


